services:
  - type: web
    name: taskpath-backend
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_APPLICATION_NAME
        value: TaskPathBackend
      - key: SERVER_PORT
        value: 8080
      - key: MONGODB_URI
        sync: false   # se configurará en Render UI
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false